# Generated by ariadne-codegen
# Source: ariadne/queries.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class GuideDataQuery(BaseModel):
    guides: List["GuideDataQueryGuides"]


class GuideDataQueryGuides(BaseModel):
    id: Any
    brand_id: Optional[Any] = Field(alias="brandId")
    description: Optional[str]
    is_discoverable: bool = Field(alias="isDiscoverable")
    brand: Optional["GuideDataQueryGuidesBrand"]
    target_viewpoints: List["GuideDataQueryGuidesTargetViewpoints"] = Field(
        alias="targetViewpoints"
    )


class GuideDataQueryGuidesBrand(BaseModel):
    id: Any
    name: str
    description: Optional[str]


class GuideDataQueryGuidesTargetViewpoints(BaseModel):
    id: Any
    note: Optional[str]
    target_ballot_item_id: Optional[Any] = Field(alias="targetBallotItemId")
    source_guide_id: Any = Field(alias="sourceGuideId")
    target_viewpoint_id: Optional[Any] = Field(alias="targetViewpointId")
    target_ballot_item: Optional[
        "GuideDataQueryGuidesTargetViewpointsTargetBallotItem"
    ] = Field(alias="targetBallotItem")
    selections: List["GuideDataQueryGuidesTargetViewpointsSelections"]


class GuideDataQueryGuidesTargetViewpointsTargetBallotItem(BaseModel):
    race: Optional["GuideDataQueryGuidesTargetViewpointsTargetBallotItemRace"]
    measure: Optional["GuideDataQueryGuidesTargetViewpointsTargetBallotItemMeasure"]


class GuideDataQueryGuidesTargetViewpointsTargetBallotItemRace(BaseModel):
    id: Any
    name: Optional[str]


class GuideDataQueryGuidesTargetViewpointsTargetBallotItemMeasure(BaseModel):
    id: Any
    name: str


class GuideDataQueryGuidesTargetViewpointsSelections(BaseModel):
    id: Any
    rank: Optional[int]
    weight: int
    note: Optional[str]
    candidacy_id: Optional[Any] = Field(alias="candidacyId")
    viewpoint_id: Any = Field(alias="viewpointId")


GuideDataQuery.model_rebuild()
GuideDataQueryGuides.model_rebuild()
GuideDataQueryGuidesTargetViewpoints.model_rebuild()
GuideDataQueryGuidesTargetViewpointsTargetBallotItem.model_rebuild()
