# Generated by ariadne-codegen
# Source: ariadne/queries.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class InsertBrand(BaseModel):
    insert_brands_one: Optional["InsertBrandInsertBrandsOne"] = Field(
        alias="insertBrandsOne"
    )


class InsertBrandInsertBrandsOne(BaseModel):
    id: Any
    name: str
    description: Optional[str]
    group_brand_relationships: List[
        "InsertBrandInsertBrandsOneGroupBrandRelationships"
    ] = Field(alias="groupBrandRelationships")


class InsertBrandInsertBrandsOneGroupBrandRelationships(BaseModel):
    id: Any
    group_id: Any = Field(alias="groupId")


InsertBrand.model_rebuild()
InsertBrandInsertBrandsOne.model_rebuild()
