# Generated by ariadne-codegen
# Source: ariadne/queries.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class InsertViewpoint(BaseModel):
    insert_viewpoints_one: Optional["InsertViewpointInsertViewpointsOne"] = Field(
        alias="insertViewpointsOne"
    )


class InsertViewpointInsertViewpointsOne(BaseModel):
    id: Any


InsertViewpoint.model_rebuild()
