# Generated by ariadne-codegen
# Source: ariadne/queries.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class InsertSelection(BaseModel):
    insert_selections_one: Optional["InsertSelectionInsertSelectionsOne"] = Field(
        alias="insertSelectionsOne"
    )


class InsertSelectionInsertSelectionsOne(BaseModel):
    id: Any


InsertSelection.model_rebuild()
