# Generated by ariadne-codegen
# Source: ariadne/queries.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateViewpointsMany(BaseModel):
    update_viewpoints_many: Optional[
        List[Optional["UpdateViewpointsManyUpdateViewpointsMany"]]
    ] = Field(alias="updateViewpointsMany")


class UpdateViewpointsManyUpdateViewpointsMany(BaseModel):
    affected_rows: int = Field(alias="affectedRows")
    returning: List["UpdateViewpointsManyUpdateViewpointsManyReturning"]


class UpdateViewpointsManyUpdateViewpointsManyReturning(BaseModel):
    id: Any


UpdateViewpointsMany.model_rebuild()
UpdateViewpointsManyUpdateViewpointsMany.model_rebuild()
