# Generated by ariadne-codegen
# Source: ariadne/queries.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateSelection(BaseModel):
    update_selections_by_pk: Optional["UpdateSelectionUpdateSelectionsByPk"] = Field(
        alias="updateSelectionsByPk"
    )


class UpdateSelectionUpdateSelectionsByPk(BaseModel):
    id: Any
    candidacy_id: Optional[Any] = Field(alias="candidacyId")
    weight: int
    rank: Optional[int]
    note: Optional[str]


UpdateSelection.model_rebuild()
