# Generated by ariadne-codegen
# Source: ariadne/queries.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateSelectionsMany(BaseModel):
    update_selections_many: Optional[
        List[Optional["UpdateSelectionsManyUpdateSelectionsMany"]]
    ] = Field(alias="updateSelectionsMany")


class UpdateSelectionsManyUpdateSelectionsMany(BaseModel):
    affected_rows: int = Field(alias="affectedRows")
    returning: List["UpdateSelectionsManyUpdateSelectionsManyReturning"]


class UpdateSelectionsManyUpdateSelectionsManyReturning(BaseModel):
    id: Any


UpdateSelectionsMany.model_rebuild()
UpdateSelectionsManyUpdateSelectionsMany.model_rebuild()
