# Generated by ariadne-codegen
# Source: ariadne/queries.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateBrand(BaseModel):
    update_brands_by_pk: Optional["UpdateBrandUpdateBrandsByPk"] = Field(
        alias="updateBrandsByPk"
    )


class UpdateBrandUpdateBrandsByPk(BaseModel):
    id: Any
    name: str


UpdateBrand.model_rebuild()
