# Generated by ariadne-codegen
# Source: ariadne/queries.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateGuide(BaseModel):
    update_guides_by_pk: Optional["UpdateGuideUpdateGuidesByPk"] = Field(
        alias="updateGuidesByPk"
    )


class UpdateGuideUpdateGuidesByPk(BaseModel):
    id: Any
    description: Optional[str]
    is_discoverable: bool = Field(alias="isDiscoverable")


UpdateGuide.model_rebuild()
